### ISSUE TITLE
Question about Flow_SCALE during testing

### ISSUE THREAD

**Issue by LiuzhuForFun** [vt-vl-lab/DF-Net#13]
Hi Mr zou,firstly thanks for you work on this field.It inspired me a lot. the code:
   pred0 = cv2.resize(pred_flow[:,:,0], (W, H), interpolation=cv2.INTER_LINEAR) * (1.0*W/old_W)
    pred1 = cv2.resize(pred_flow[:,:,1], (W, H), interpolation=cv2.INTER_LINEAR) * (1.0*H/old_H)
    pred = np.stack((pred0, pred1), axis=-1) * FLOW_SCALE
What does the Flow_SCALE mean?

**Comment by LiuzhuForFun** [comment]
FLow_SCALE =5.0?Why? Thanks again!

**Comment by LiuzhuForFun** [comment]
I also have a question: Can I use the tensorflow's function of resize (tf.resize( ))?

**Comment by LiuzhuForFun** [comment]
mean = [104.920005, 110.1753, 114.785955]
Is it the mean of kitti,cityscape or flyingchairs?

**Comment by Yuliang-Zou** [comment]
1) I used the settings from UnFlow paper, which uses `FLOW_SCALE=5.0`
2) You should be able to use TF function for that
3) I don't remember, seems that it is from ImageNet.
