### ISSUE TITLE
How to cacluate the EPE for the optical flow 2012/2015 test sets?

### ISSUE THREAD

**Issue by yasser-taha** [vt-vl-lab/DF-Net#16]
Hello @Yuliang-Zou ,
In the DF-Net paper, it was mentioned that the EPE you achieve on the KITTI 2012 test set is 4.4.
I am not sure how you can obtain this error without the flow_occ ground truth label which is not available for the test set. I'm definitely missing something here but I don't know what. 

Also by following the code in test_flow_2012.py, I found that the EPE for the test is ignored here:
```
# Save for eval
            if 'test' in FLAGS.dataset_dir:
                _, scaled_pred = compute_flow_error(np.array(raw_im0)[:,:,:2], pred_flow_val[0,:,:,:], np.array(raw_im0)[:,:,0])
                png_name = os.path.join(FLAGS.output_dir, new_files[t][0].split('/')[-1])
                write_flow_png(png_name, scaled_pred)
```
so the `compute_flow_error` function should return the EPE and the scaled_pred but the EPE is ignored here. On the contrary, for the train set, in the same file, its is used to calculate the EPE in `errs[t]`:

```
# Only for training set
            if 'train' in FLAGS.dataset_dir:
                # no occlusion
                #gt_flow, mask = get_flow(new_files[t][0].replace('colored_0', 'flow_noc'))
                # all
                gt_flow, mask = get_flow(new_files[t][0].replace('colored_0', 'flow_occ'))
                errs[t], scaled_pred = compute_flow_error(gt_flow, pred_flow_val[0,:,:,:], mask)
```
Any clarification would be of great help!

**Comment by Yuliang-Zou** [comment]
Hi @YasserTahaSW , we don't have the ground truth label for test set, so we can only save it as required format and then upload to their server for evaluation.

**Comment by yasser-taha** [comment]
oh, my bad! 
But why does the test set of kitti rawdata for depth have results then? 
I mean the results for the test set available here: `data/kitti/test_files_eigen.txt` and evaluated in `eval_depth.py`

**Comment by Yuliang-Zou** [comment]
Originally, KITTI does not have depth estimation task on their server. But KITTI raw has stereo information, so you can actually compute sparse depth ground truth.

**Comment by yasser-taha** [comment]
now i got it! Thanks a lot @Yuliang-Zou ! :)
