### ISSUE TITLE
Testing on Make3D/ Training on cityscape

### ISSUE THREAD

**Issue by yasser-taha** [vt-vl-lab/DF-Net#17]
Hello @Yuliang-Zou 
I have three questions:
1- To test the depth on the kitti dataset, the images were scaled to (height= 160, width = 576). 
I am interested to know whether you also rescaled the make3D images using the same values!

2- Should the mean values in the `preprocess_image`  function in the Baselearner, be changed during the testing/eval of the make3D.
These are the mean values:
`mean = [104.920005, 110.1753, 114.785955]`

3- should these mean values be changed when training on kitti+cityscape dataset. Or is cityscape already included?

**Comment by Yuliang-Zou** [comment]
1) I remember I do the scaling for Make3D as well
2) and 3) The mean values are from ImageNet data statistics, so I use it as a fixed value.

**Comment by yasser-taha** [comment]
Thanks a lot @Yuliang-Zou! For point 1: did you use the same values (160,576)?

**Comment by Yuliang-Zou** [comment]
Yes I used the same values

**Comment by yasser-taha** [comment]
Thank you! :)
