### ISSUE TITLE
saving depth images

### ISSUE THREAD

**Issue by yasser-taha** [vt-vl-lab/DF-Net#18]
Hi @Yuliang-Zou , 
I have a problem wit saving the depth images correctly. 
To save the depth images, I added the following code in the `test_kitti_depth.py`:
```
            for b in range(FLAGS.batch_size):
                idx = t + b
                if idx >= len(test_files):
                    break
                pred_all.append(pred['depth'][b,:,:,0])

                #added the following two lines

                png_name = os.path.join(FLAGS.output_dir, str(idx)+'.jpg')
                pyplot.imsave(png_name, (pred['depth'][b,:,:,0]),vmin = 1e-3, vmax = 80)
```
The problem i get is that the saved images are not the same as the one posted on your[ project page](http://yuliang.vision/DF-Net/results/raw/index.html). They have the same overall structure but the overall intensities are different. 
For example, image 57 in the test split should look like:
![57_DF](https://user-images.githubusercontent.com/17002515/59034800-2fb8da80-886c-11e9-86c5-0af25536b64c.png)
 However, my output is:
![57_mine](https://user-images.githubusercontent.com/17002515/59034816-3e9f8d00-886c-11e9-90fe-d0cb42d0c1bc.png)

The car and the trees are there but the intensities are completely different...

So, I wonder if you can point out whats wrong or if you can share the code where you saved the images.

Thanks a lot!

**Comment by Yuliang-Zou** [comment]
You need to use some colormap to visualize it (in matplotlib). I don't have the exact code right now, but I remember the name of that colormap is "plasma". You can refer to this [code](https://github.com/tinghuiz/SfMLearner/blob/master/demo.ipynb), note that they use a different colormap.

**Comment by yasser-taha** [comment]
Thanks a lot @Yuliang-Zou.
I edited the aforementioned code to be as follows and it worked:
```
            for b in range(FLAGS.batch_size):
                idx = t + b
                if idx >= len(test_files):
                    break
                pred_all.append(pred['depth'][b,:,:,0])
                image = (normalize_depth_for_display(pred['depth'][b,:,:,0],cmap='plasma'))
                plt.imsave(os.path.join(FLAGS.output_dir, str(t+b)+'.jpg'),image)
```
And i just had to import these two modules:
```
from core.utils import normalize_depth_for_display
import matplotlib.pyplot as plt
```
