### ISSUE TITLE
Result visualization

### ISSUE THREAD

**Issue by wangq95** [vt-vl-lab/DF-Net#19]
Hi, thanks for your works. Can you share the core to convert the predicted result in gray scale to colorful result like this?
![image](https://user-images.githubusercontent.com/33200440/63237717-b844f580-c275-11e9-9362-d1cc7712a1ee.png)

Best regards.

**Comment by Yuliang-Zou** [comment]
Hi @QianshengGu , you can refer to [this](https://github.com/vt-vl-lab/DF-Net/issues/18)

**Comment by wangq95** [comment]
Thanks a lot! @Yuliang-Zou
