### ISSUE TITLE
Test pose code

### ISSUE THREAD

**Issue by SaiK95** [vt-vl-lab/DF-Net#20]
Hi, 

Great work! Can you please share a script to do pose evaluation (similar to test_kitti_depth.py)? I tried loading the weights and creating the model with image sizes as [128, 416], [256, 832], [384, 1248], but all of them resulted in size mismatch errors. 

Thanks, 
Sai

**Comment by Yuliang-Zou** [comment]
Thanks for your interest. However, I am currently busy with CVPR submission. I do plan to add the pose evaluation code but I might not have time until the end of this year.

**Comment by SaiK95** [comment]
@Yuliang-Zou Thanks, I understand. 
I'm currently working towards CVPR as well and as per the new [reproducability standards](https://www.cs.mcgill.ca/~jpineau/ReproducibilityChecklist.pdf), it'd be great if I can run inference on all the models in this area of work. Since DF-Net is one of the SOTA ones, can you let me know what the image sizes are? I can run the inference on my own. 

Thanks for your help,
Sai

**Comment by Yuliang-Zou** [comment]
Hi @SaiK95 , sorry for the delay. The size is 320x1152, you can find it in the data preparation code [here](https://github.com/vt-vl-lab/DF-Net/blob/master/data/prepare_train_data.py#L14).

**Comment by SaiK95** [comment]
Hi @Yuliang-Zou, sorry to bother you again. 

Couple of quick questions: 

1. I think one of the reasons I was getting a size mismatch error was the sequence length was 2 in the DFLearner() class. After changing it to 5, that error was avoided. Can you clarify why you double the number of pose outputs in the pose network? Is it to get forward and backward poses? 
![image](https://user-images.githubusercontent.com/29799842/67906969-5261cd80-fb44-11e9-94dd-900457508d3c.png)

2. As of now, by using a sequence length of 5, the number of output channels of the pose_pred layer is 24. But the saved weights has 48 channels. Can you clarify this please?

**Comment by Yuliang-Zou** [comment]
Hi @SaiK95 , since I am predicting both directions, the number will be doubled. (Actually, I should use the same pose but apply the inverse transform based on it. But at that time, I just chose to predict both directions)

**Comment by SaiK95** [comment]
Nevermind, I found the issue. I had to pass sequence length as 5 while calling the setup_inference() function. My bad :)

Thanks for the clarification on doubling the number of pose predictions.
