### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by lhoangan** [vt-vl-lab/DF-Net#3]
Could you please specify which part of the KITTI to be downloaded and how the dataset should be organized? I am having this error

```
tensorflow.python.framework.errors_impl.NotFoundError: misc/raw/2011_09_30_drive_0028_sync_03/0000002522_cam.txt
	 [[Node: data_loading/ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](data_loading/TextLineReaderV2, data_loading/input_producer_1)]]
```
I've tried downloading the raw+sync [KITTI](http://www.cvlibs.net/datasets/kitti/raw_data.php), using the link at this line:
`Download the raw dataset download script (1 MB) (thanks to Omid Hosseini for sharing!)`

and put them under `raw` folder, and passed in `--dataset_dir=raw`

The structure appears to be : like `raw/2011_09_30/2011_09_30_drive_0028_sync/` and inside it are these directories:
`image_00 ,  image_01 ,  image_02 , image_03 ,  oxts ,  velodyne_points`

There's no `2011_09_30_drive_0028_sync_03` or `0000002522_cam.txt` to be found, maybe I need to download from different link or is there any pre-processing / re-organizing required?

**Comment by Yuliang-Zou** [comment]
Have you run this `./misc/prepare.sh`? It should download both the initialization model and pre-processed dataset for you.
