### ISSUE TITLE
Receive loss nan when training

### ISSUE THREAD

**Issue by lhoangan** [vt-vl-lab/DF-Net#4]
I've started training the network when I received all nan value for loss from the first iteration. 
```
python train_df.py --dataset_dir=misc/dataset/kitti_5frame_1152_320 --checkpoint_dir=checkpoint
```
I'm not sure if it's the effect of using 1 GPU and setting batch size to 1. Do you have any insight to this?

```
{'alpha_image_loss': 0.85,
 'batch_size': 1,
 'beta1': 0.9,
 'checkpoint_dir': 'checkpoint',
 'ckpt_dp': 'misc/pretrained/cs_5frame_pre',
 'ckpt_flow': 'misc/pretrained/unflowc_pre',
 'ckpt_pose': None,
 'continue_train': True,
 'cross_consistency': 0.5,
 'dataset_dir': 'misc/dataset/kitti_5frame_1152_320',
 'depth_consistency': 0.2,
 'fix_pose': False,
 'flow_consistency': 0.2,
 'flow_smooth_weight': 3.0,
 'img_height': 320,
 'img_width': 1152,
 'learning_rate': 0.0001,
 'max_steps': 100000,
 'num_gpus': 1,
 'save_latest_freq': 5000,
 'scale_normalize': False,
 'seq_length': 5,
 'smooth_weight': 3.0,
 'summary_freq': 100}
WARNING:tensorflow:From /home/hale/TrimBot/projects/DF-Net/core/DFLearner.py:475: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2018-09-18 14:42:53.853974: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-18 14:42:53.854021: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-18 14:42:53.854031: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-09-18 14:42:53.854049: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-18 14:42:53.854057: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-09-18 14:42:54.272654: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 11.91GiB
Free memory: 10.38GiB
2018-09-18 14:42:54.272711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-09-18 14:42:54.272721: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-09-18 14:42:54.272734: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
Trainable variables: 
depth_net_res50/Conv/weights:0
depth_net_res50/Conv/biases:0
...
flownet_c/flow3_up2/biases:0
flownet_c/flow2/weights:0
flownet_c/flow2/biases:0
('parameter_count =', 99228758)
Resume flow_net from previous checkpoint: misc/pretrained/unflowc_pre
Resume depth_net and pose_net from previous checkpoint: misc/pretrained/cs_5frame_pre
2018-09-18 14:44:23.043925: I tensorflow/core/kernels/cuda_solvers.cc:137] Creating CudaSolver handles for stream 0x3f12fac0
2018-09-18 14:44:30.411640: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.22GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-09-18 14:44:31.111228: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1378 get requests, put_count=1240 evicted_count=1000 eviction_rate=0.806452 and unsatisfied allocation rate=0.898403
2018-09-18 14:44:31.111302: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
2018-09-18 14:45:26.740231: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2095 get requests, put_count=2145 evicted_count=1000 eviction_rate=0.4662 and unsatisfied allocation rate=0.464439
2018-09-18 14:45:26.740317: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
/home/hale/TrimBot/projects/DF-Net/core/flowlib.py:257: RuntimeWarning: invalid value encountered in greater
  idxUnknow = (abs(u) > UNKNOWN_FLOW_THRESH) | (abs(v) > UNKNOWN_FLOW_THRESH)
Epoch: [ 1] [  100/34841] time: 2.5545/it loss: nan
Epoch: [ 1] [  200/34841] time: 2.1562/it loss: nan
Epoch: [ 1] [  300/34841] time: 2.1207/it loss: nan
Epoch: [ 1] [  400/34841] time: 2.1037/it loss: nan
Epoch: [ 1] [  500/34841] time: 2.1077/it loss: nan
Epoch: [ 1] [  600/34841] time: 2.1089/it loss: nan
Epoch: [ 1] [  700/34841] time: 2.1245/it loss: nan
Epoch: [ 1] [  800/34841] time: 2.1175/it loss: nan
Epoch: [ 1] [  900/34841] time: 2.1038/it loss: nan
Epoch: [ 1] [ 1000/34841] time: 2.1104/it loss: nan
...
```

**Comment by Yuliang-Zou** [comment]
I just tried using 1 GPU and setting batch size to 1, it worked for me. Are you using python2.7 instead of python3.x?

**Comment by lhoangan** [comment]
It was python3.6. I've created an anaconda environment for 3.6 and installed the corresponding tf 1.2 into it.

**Comment by Yuliang-Zou** [comment]
Are you sure the data loading is correct? Can you try checking the tensorboard visualization?

**Comment by lhoangan** [comment]
The `scale0_projected_image_src2tgt_0/image/0` and similars look fine. Some of them, like `scale0_flow_image_scr2tgt_0` are all black. Do you have any in mind to check?

Besides, `depth_consistency_loss` , `dp_pixel_loss`, and `dp_smooth_loss` also look fine. `flow_*_loss`  and `cross_consistency_loss` are all nan

**Comment by Yuliang-Zou** [comment]
Seems the issue lies in the flow prediction. Can you check if the flow visualization in tensorboard is reasonable or not? I think you might load the model in a wrong way?

**Comment by lhoangan** [comment]
As said, all the `scale*_flow*_src2tgt_*` in the visualization are all black. I'm not sure if it's the data loading or the model loading. Do you have any specific part to check in mind?

**Comment by Yuliang-Zou** [comment]
Can you test the initialization flow model on KITTI2012 or KITTI2015? See [here](https://github.com/vt-vl-lab/DF-Net#testing)

**Comment by lhoangan** [comment]
I've run testing with the given pretrained model, using this command
```
python test_flownet_2012.py --dataset_dir=./flow2012/training --ckpt_file= misc/pretrained/unflowc_pre --split="val"
```
And this is the output
```
WARNING:tensorflow:From test_flownet_2012.py:77: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2018-09-22 10:48:51.487982: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-22 10:48:51.488009: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-22 10:48:51.488018: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-09-22 10:48:51.488026: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-09-22 10:48:51.488033: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-09-22 10:48:51.781908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 11.91GiB
Free memory: 10.02GiB
2018-09-22 10:48:51.781968: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-09-22 10:48:51.781981: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-09-22 10:48:51.781995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
2018-09-22 10:49:09.074069: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2018-09-22 10:49:13.740655: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
2018-09-22 10:49:18.416241: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for
...
```
I'm not sure if there's something wrong with my command, or failure in loading the model?

**Comment by lhoangan** [comment]
I run the inference with this command
```
python test_flownet_2012.py --dataset_dir=/home/hale/Datasets/KITTI/data_stereo_flow/training --ckpt_file=misc/pretrained/unflowc_pre --split="val" output_dir=./output
```
The results are:
```
processing unflowc_pre: 0/194
processing unflowc_pre: 100/194
(valid) endpoint error
 2544.6155
```
And here's the output image 000000_10.jpg

![000000_10](https://user-images.githubusercontent.com/9334094/45930242-f2baeb00-bf5d-11e8-925b-f7f765e9dae0.jpg)

**Comment by Yuliang-Zou** [comment]
This is what I got:
```
ylzou@werbos:~/paper_code/eccv2018dfnet$ python test_flownet_2012.py --ckpt_file=pretrained/unflowc_pre
WARNING:tensorflow:From test_flownet_2012.py:77: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2018-09-23 20:07:31.963138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:938] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:8d:00.0
Total memory: 11.92GiB
Free memory: 11.86GiB
2018-09-23 20:07:31.963220: I tensorflow/core/common_runtime/gpu/gpu_device.cc:959] DMA: 0
2018-09-23 20:07:31.963236: I tensorflow/core/common_runtime/gpu/gpu_device.cc:969] 0:   Y
2018-09-23 20:07:31.963253: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1028] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:8d:00.0)
processing unflowc_pre: 0/194
processing unflowc_pre: 100/194
(valid) endpoint error
    3.6822
```

Maybe there are some issues when you compile the CUDA ops?

**Comment by lhoangan** [comment]
The compilation didn't issue any error. I supposed if there's an error, the whole network would not work, would it? Do you have any idea how that can be tested?

**Comment by lhoangan** [comment]
The compilation didn't issue any error. I supposed if there's an error, the whole network would not work, would it? Do you have any idea how that can be tested?

**Comment by Yuliang-Zou** [comment]
What if you evaluate using the pre-trained DF-Net model? If this one also gives you bad results, then probably there is something wrong with the custom op.

**Comment by lhoangan** [comment]
I am a little confused. The results that I posted were when using pre-trained weight. Is it the same with one that you are talking about? Could you please clarify this point?

**Comment by Yuliang-Zou** [comment]
Oh, that's from the initialization model. The one I want you to test is the `dfnet` model.

**Comment by lhoangan** [comment]
I'm sorry, I am quite new to tensorflow, so I still don't have a clue what the difference is. Can you provide the command to do that?

**Comment by Yuliang-Zou** [comment]
Can you do this?
`python test_flownet_2012.py --ckpt_file=pretrained/dfnet`
(and remember to specify the path to the dataset)

**Comment by lhoangan** [comment]
Here's the result

```
WARNING:tensorflow:From test_flownet_2012.py:77: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Please use tf.global_variables instead.
2018-10-01 15:07:59.995402: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-01 15:07:59.995429: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-01 15:07:59.995438: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-10-01 15:07:59.995446: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-10-01 15:07:59.995454: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-10-01 15:08:00.293067: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 11.91GiB
Free memory: 10.31GiB
2018-10-01 15:08:00.293123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-10-01 15:08:00.293135: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-10-01 15:08:00.293148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
processing dfnet: 0/194
processing dfnet: 100/194
(valid) endpoint error
 4497.6474
```
So I guess there's something wrong with the custom op? Do you have any thought on how to check where the error is?

**Comment by roboticsbala** [comment]
Hi, I also so have the same issue. I get the the following error while training 
idxUnknow = (abs(u) > UNKNOWN_FLOW_THRESH) | (abs(v) > UNKNOWN_FLOW_THRESH)
Epoch: [ 1] [  100/34841] time: 2.5545/it loss: nan
And when I run flowNet, the endpoint error is very high (2265.xxx) 
I am using cuda 8.0, tensorflow-gpu 1.2.0, cudnn5.0
@lhoangan Did you manage to get the issue solved?

**Comment by roboticsbala** [comment]
@lhoangan Did you have any issues while trying to run the depth inference for the first time? Something related to building ops (backward_warp_op.so) or get the error: __builtin_ia32_monitorx" is undefined?

**Comment by Yuliang-Zou** [comment]
@roboticsbala So you have tested the pre-trained models on KITTI flow datasets?

I am not sure if that's the case. I am using cudnn6.0 for cuda8.0

**Comment by lhoangan** [comment]
@roboticsbala no, the issue is still hanging there with me, in my case building ops doesn't give any error. @Yuliang-Zou do you have any insight what else could cause the error? Could you try to clone and run the code on a different machine to see if it persists?

**Comment by roboticsbala** [comment]
@Yuliang-Zou Yes I did try the pre-trained models in KITTI flow2012 and flow2015. Jus that the endpoint error is very large (when compared to the value that you got 3.6822)

@lhoangan I get the following error when I try to build the ops 
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined
But if I add the flags -D_MWAITXINTRIN_H_INCLUDED, -D_FORCE_INLINES to the cmd in ops.py
'nvcc -std=c++11 -c -gencode=arch=compute_30,code=sm_30 -o backward_warp_op.cu.o backward_warp_op.cu.cc -I /root/anaconda3/envs/df_net_gpu/lib/python3.6/site-packages/tensorflow/include -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC'  it works.

Can you tell me what version of gcc, g++, tensorflow, tensorflow-gpu, nvcc packages you're using?

**Comment by lhoangan** [comment]
python 3.6
gcc/g++ version 4.8.4
tensorflow_gpu-1.2.0-cp36-cp36m-linux_x86_64.whl
nvcc 8.0.61

**Comment by roboticsbala** [comment]
> @roboticsbala So you have tested the pre-trained models on KITTI flow datasets?
> 
> I am not sure if that's the case. I am using cudnn6.0 for cuda8.0

Sorry, I have libcudnn5. If I use cudnn6.0 I get the error ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory.

**Comment by roboticsbala** [comment]
@Yuliang-Zou Also if cudnn6.0 is used I also get the issue
Loaded runtime CuDNN library: 6021 (compatibility version 6000) but source was compiled with 5110 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

**Comment by roboticsbala** [comment]
> python 3.6
> gcc/g++ version 4.8.4
> tensorflow_gpu-1.2.0-cp36-cp36m-linux_x86_64.whl
> nvcc 8.0.61

@lhoangan Thank you for the reply. Can you also confirm the libcudnn version that you have? Using the cmd 
ldconfig -p | grep libcudnn

**Comment by roboticsbala** [comment]
When I try to run FlowNet2015 using the following cmd,
python test_flownet_2015.py --dataset_dir=dataset/KITTI/flow2015/training --output_dir=prediction --ckpt_file=models/pretrained/unflowc_pre

I get the following result:
processing unflowc_pre: 0/200
test_flownet_2015.py:45: RuntimeWarning: invalid value encountered in sqrt
gt_mag = np.sqrt(np.sum(np.square(gt_flow), axis=-1))
processing unflowc_pre: 100/200
(valid) endpoint error,   f1 score
 3570.1853,     1.0000

On running FlowNet2012 using the following cmd,
python test_flownet_2012.py --dataset_dir=dataset/KITTI/flow2012/training --output_dir=prediction --ckpt_file=models/pretrained/unflowc_pre

I get the following result:
processing unflowc_pre: 0/194
processing unflowc_pre: 100/194
(valid) endpoint error
 3013.3140

And the endpoint error values are not consistent (they keep changing every trial).

**Comment by Yuliang-Zou** [comment]
My system settings are:
python3.6
gcc/g++ 4.9.4
tensorflow 1.2.0
nvcc V8.0.44
cuda-8.0
cudnn-8.0-v6.0

Before I made it public, I have asked my labmate to test the code, and it seems that he has no problems. I will double check with him. Sorry for any inconvenience.

**Comment by Yuliang-Zou** [comment]
@lhoangan @roboticsbala Can you let me know your GPU type? My labmate said he can run it with 1080 Ti or Titan X.

**Comment by lhoangan** [comment]
@Yuliang-Zou I tried it on a TitanX
@roboticsbala I'm using cuDNNv5.1

**Comment by roboticsbala** [comment]
> @lhoangan @roboticsbala Can you let me know your GPU type? My labmate said he can run it with 1080 Ti or Titan X.

@Yuliang-Zou I'm also trying it on 1080 Ti

**Comment by roboticsbala** [comment]
> @Yuliang-Zou I tried it on a TitanX
> @roboticsbala I'm using cuDNNv5.1

@lhoangan Thanks. And definitely other versions are not working.

**Comment by roboticsbala** [comment]
@lhoangan @Yuliang-Zou Can you please verify the loaded model (graph from tensorboard). To me it looks good.
[graph.zip](https://github.com/vt-vl-lab/DF-Net/files/2468479/graph.zip)

**Comment by roboticsbala** [comment]
> My system settings are:
> python3.6
> gcc/g++ 4.9.4
> tensorflow 1.2.0
> nvcc V8.0.44
> cuda-8.0
> cudnn-8.0-v6.0
> 
> Before I made it public, I have asked my labmate to test the code, and it seems that he has no problems. I will double check with him. Sorry for any inconvenience.

@Yuliang-Zou GPU libs in tensorflow-gpu 1.2.0 were complied using libcudnn5. So if you're using  tensorflow 1.2.0 with libcudnn6 you should get the following error.
ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory.

And if you're trying to link a different libcudnn.so .* to libcudnn.so.5 (Example: sudo ln -s libcudnn.so .6 libcudnn.so.5). You should still get the following error.
Loaded runtime CuDNN library: 6021 (compatibility version 6000) but source was compiled with 5110 (compatibility version 5100). If using a binary install, upgrade your CuDNN library to match. If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

Can you also confirm the libcudnn version that you have? Using the cmd
ldconfig -p | grep libcudnn

**Comment by Yuliang-Zou** [comment]
Hi @roboticsbala , I don't have the root access, so `ldconfig -p | grep libcudnn` will not give me the information.

I use `.bashrc` file to add path to my cudnn lib, 
```
export CUDA_ROOT=/home/ylzou/install/cuda
export LD_LIBRARY_PATH=/home/ylzou/install/cuda/lib64:$LD_LIBRARY_PATH
```

So maybe I am not using cudnn at all? But tensorflow requires us to use cudnn to import, right?

**Comment by roboticsbala** [comment]
@Yuliang-Zou That's right. tensorflow-gpu requires some version of cudnn or other, depending on it's version. For example, tf 1.2.0 requires cudnn 5, tf 1.3.0 requires cudnn 6, tf 1.7.0 requires cudnn 9.

**Comment by roboticsbala** [comment]
@Yuliang-Zou Is it possible for you to share the .so and cu.o files of UnFlow ops?

**Comment by Yuliang-Zou** [comment]
Yes, @roboticsbala . I put them [here](https://filebox.ece.vt.edu/~ylzou/eccv2018dfnet/ops.tar)

**Comment by roboticsbala** [comment]
@Yuliang-Zou @lhoangan I was hoping to get some runtime errors indicating the dependencies that we missed but unfortunately I get the following error when I load the .so files itself.
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: undefined symbol: _ZNK10tensorflow15TensorShapeBaseINS_11TensorShapeEE8dim_sizeEi

**Comment by roboticsbala** [comment]
@Yuliang-Zou The UnFlow package from https://github.com/simonmeister/UnFlow has a tensorflow-gpu requirement of at least 1.7, whereas in your DF-Net package states that it can work only with tensorflow-gpu 1.2. Can you please explain if the Unflow files included in DF-Net package are different from the original implementation from Simon Meister?

**Comment by Yuliang-Zou** [comment]
I used the early version of the implementation from UnFlow, so it can only
work with 1.2 for now. I can try to update the code to 1.7+, but that would
take some time since I am currently busy with a cvpr submission.

**Comment by roboticsbala** [comment]
@Yuliang-Zou When I use your .so files I get the following error 
RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6

I guess the .so files you provided were compiled using python 3.5 and not python 3.6

**Comment by Yuliang-Zou** [comment]
That's weird. I just checked the version on my cluster, it is indeed python3.6...

**Comment by roboticsbala** [comment]
@lhoangan If you haven't solved the issue yet, try removing "-gencode=arch=compute_30,code=sm_30" from the nvcc_cmd in ops.py. And it works.

@Yuliang-Zou Thank you for the support.

processing unflowc_pre: 0/194
processing unflowc_pre: 100/194
(valid) endpoint error
    3.6822

**Comment by lhoangan** [comment]
@roboticsbala : thanks for the tip. It works now for me, I can get the same 3.6822 result. Just out of curiosity, what's wrong with the original setup?
@Yuliang-Zou : The training is also working now, the first few losses are 3086.788, 2212.561, 2580.432. At least, they're not NAN any more. Just to be sure that everything is fine now,  is it the normal behavior of the loss?

**Comment by Yuliang-Zou** [comment]
Hi @lhoangan , that's a reasonable value. Since the census transform based photometric loss is quite large.

**Comment by roboticsbala** [comment]
@Yuliang-Zou Can you share the training loss log on kitti_5frame_1152_320? 
The total loss seems to not decrease consistently even after 2 epochs.
Epoch: [ 2] [16880/17420] time: 1.9740/it loss: 3601.947
Epoch: [ 2] [16980/17420] time: 1.9848/it loss: 3265.528
Epoch: [ 2] [17080/17420] time: 1.9767/it loss: 2984.375
Epoch: [ 2] [17180/17420] time: 1.9989/it loss: 3197.285
Epoch: [ 2] [17280/17420] time: 2.0004/it loss: 2890.231
Epoch: [ 2] [17380/17420] time: 1.9958/it loss: 3052.492
 [*] Saving checkpoint to models/kitti_train...
Epoch: [ 3] [   60/17420] time: 2.3420/it loss: 3433.853
Epoch: [ 3] [  160/17420] time: 2.0091/it loss: 3147.344
Epoch: [ 3] [  260/17420] time: 2.3603/it loss: 3410.281
Epoch: [ 3] [  360/17420] time: 2.0021/it loss: 3077.572

**Comment by Yuliang-Zou** [comment]
@roboticsbala I also observed similar loss log during training. You will not see the loss decreasing consistently from the log, but if you use tensorboard to visualize the curve (and set a proper smoothing factor), you should see it slowly decreasing.

**Comment by roboticsbala** [comment]
After 2 days of training, this is the status
![image](https://user-images.githubusercontent.com/10575034/47211480-d7dd6a00-d395-11e8-9962-d9527c9e05f6.png)
![image](https://user-images.githubusercontent.com/10575034/47211569-12470700-d396-11e8-810e-355855c92a69.png)
The cross consistency loss and flow smooth loss seem to keep increasing.

![image](https://user-images.githubusercontent.com/10575034/47211614-39053d80-d396-11e8-9177-2e69b3bb8491.png)
But the total loss is gradually decreasing.

@Yuliang-Zou Can you explain why this is the case?
@lhoangan Is it same with your training as well?

**Comment by Yuliang-Zou** [comment]
@roboticsbala Yes that's basically the same as my training curve. I don't know the exact reason. Maybe because this is unsupervised learning, the proxy loss cannot truly represent how well the model is trained.

**Comment by roboticsbala** [comment]
@Yuliang-Zou Are the default parameters in train_df.py the one you used for training (in accordance to the paper)?

**Comment by roboticsbala** [comment]
@Yuliang-Zou I wasn't able to reproduce the result from the paper after re-training with KITTI dataset. I got

abs rel |  sq rel  |    rms    | log rms |     a1    |     a2    |    a3
0.4429 | 4.7569 | 12.0832 |  0.5876 | 0.3033 | 0.5608 | 0.7662

And the paper states

abs rel |  sq rel  |   rms    | log rms |     a1    |     a2    |    a3
0.1452 | 1.2904 | 5.6115 | 0.2194   | 0.8114 | 0.9394 | 0.9767

**Comment by Yuliang-Zou** [comment]
Hi @roboticsbala , did you use the validation set to pick the best model? Usually, the best model is ~30k-60k.

**Comment by roboticsbala** [comment]
@Yuliang-Zou Did you use the pre-trained models 'unflow_pre' for flownet and 'cs_5frame_pre' for depth and posenet  and continued training on kitti5frame1152_320?

**Comment by Yuliang-Zou** [comment]
Yes. I think if you pick the best model from the validation set, the result shouldn't be so bad.

**Comment by roboticsbala** [comment]
@Yuliang-Zou I am training the network with kitti5frame1152_320 dataset using 'cs_5frame_pre' and 'unflow_pre' (like you said). 

![image](https://user-images.githubusercontent.com/10575034/47660488-640e3f00-db97-11e8-8140-b0ff0022f349.png)

It kind of looks like the network is learning and de-learning. Why this phenomenon?

**Comment by Yuliang-Zou** [comment]
Sorry that I am now kind of busy with cvpr. I will be back to take a look at this later

**Comment by yasser-taha** [comment]
Hello @roboticsbala @Yuliang-Zou @lhoangan 

using this command:
`python test_flownet_2012.py --dataset_dir=/publicdata/kitti/optical_flow_2012/training/ --ckpt_file=pretrained/unflowc_pre`

I still have the same problem that I get non consistent values for the EPE error with flow_2012. I traced the reason and found out that the flownet returns different values for the same input in test_flownet_2012.py

Also, I already deleted "-gencode=arch=compute_30,code=sm_30" from the nvcc_cmd in ops.py.

Now the lines 31 to 38 in the ops.py are:
```
cuda_lib64_path_arg = "-L /system/apps/biosoft/cuda-8.0/lib64"
        nvcc_cmd = "nvcc -std=c++11 -c -o {} -I {} -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC -I $/system/apps/biosoft/cuda-8.0/include"
        nvcc_cmd = nvcc_cmd.format(" ".join([fn_cu_o, fn_cu_cc]),
                                   tf_inc)
        subprocess.check_output(nvcc_cmd, shell=True)

        gcc_cmd = "{} -std=c++11 -shared -o {} -I {} -fPIC -lcudart -D GOOGLE_CUDA=1 {}"
        gcc_cmd = gcc_cmd.format('g++',
                                " ".join([fn_so, fn_cu_o, fn_cc]),
                                 tf_inc,
                                 cuda_lib64_path_arg)
```
I am using python 3.6.1
Cuda 8.0
cudnn 5.1
tensorflow 1.2.0
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)

Do you have any idea how to fix it?

**Comment by ReekiLee** [comment]
> days of training, this is the status

Hi, @roboticsbala could you please tell me how to get these loss curve using tersorboard? Thank you in advance!
