### ISSUE TITLE
Saving Flow and Pose models separately during training

### ISSUE THREAD

**Issue by roboticsbala** [vt-vl-lab/DF-Net#5]
@Yuliang-Zou Currently the training saves the complete session (depth, flow and pose) in the checkpoint. Is there any option to save the learned flow model and pose model separately?

**Comment by Yuliang-Zou** [comment]
Oh I did not make that option. But it should be able to do so if you create separate savers [here](https://github.com/vt-vl-lab/DF-Net/blob/master/core/DFLearner.py#L472), and modify the save function accordingly [here](https://github.com/vt-vl-lab/DF-Net/blob/master/core/BaseLearner.py#L292).
