### ISSUE TITLE
About the depth consistency loss

### ISSUE THREAD

**Issue by haofeixu** [vt-vl-lab/DF-Net#6]
Hi, @Yuliang-Zou , Great work!

I seems that the depth consistency loss in your paper doesn't hold, the corresponding pixels' depth can be different between adjacent frames as the camera is also moving, right? Thanks!

**Comment by Yuliang-Zou** [comment]
The idea is that "after the warping, the depth values for those valid pixels should be the same". If you move your camera, the same pixel will not keep the same depth value.

**Comment by haofeixu** [comment]
You warp frame t+1 's depth to reconstruct frame t 's depth based on rigid flow, right? However, camera motion exists from frame t to frame t+1.

**Comment by Yuliang-Zou** [comment]
Sorry that I don't quite understand the question. Rigid flow is generated from camera motion

**Comment by haofeixu** [comment]
I mean depth is time-dependent, you can refer to SfM-Net (https://arxiv.org/pdf/1704.07804.pdf), the forward-backward consistency constraints in page 5, note the W_t(x, y) there.

**Comment by Yuliang-Zou** [comment]
Oh, I see! Yep, we should say that the 3D coordinate in the world coordinate system keeps the same, but the camera coordinate system.

**Comment by maaft** [comment]
Sorry, but I don't get the conclusion you have drawn here (i.e. why this issue is closed). As @haofeixu mentioned, the depth values will differ from frame to frame, even when their spatial positions are aligned.

I don't see the above mentioned W_t(x,y) transformation from SfM-Net applied in your source code.

Could you please elaborate? Thanks!

**Comment by Yuliang-Zou** [comment]
Hi @maaft , yes this is indeed an issue. But unfortunately, I don't have time to fix it now (due to ICCV), will come back and revisit it later.

**Comment by maaft** [comment]
Okay, thanks for letting me know! I was just wondering if I have missed something.

In the meantime, I will just reformulate the depth-consistency loss to a "rigid-flow-consistency loss" similar to the regular flow-consistency loss. This should also give some useful supervision signal.
