### ISSUE TITLE
Kitti 2015 optical flow results?

### ISSUE THREAD

**Issue by ZheC** [vt-vl-lab/DF-Net#7]
Hi Yuliang, thank you for sharing the code, that's very helpful! Can you share your results of kitti flow 2015 in the kitti evaluation format? I notice you share the Visual Results on KITTI15 but not in the format for kitti evaluation, it will be really appreciated if you can also share the results in the format of kitti evaluation. Thank you in advance!

**Comment by Yuliang-Zou** [comment]
Thanks for the interest. Let me check my disk tomorrow. I might not have the files for the model described in the paper, but the files for this re-implementation instead.

**Comment by Yuliang-Zou** [comment]
Hi @ZheC , you should be able to download the files [here](https://drive.google.com/drive/folders/1sJe22q_8pO9c9pdN-ce8zNfeUKp8CgB3?usp=sharing). The results are generated by the model from this re-implementation. The result on KITTI 2012 is better, while the result on KITTI 2015 is worse.

**Comment by ZheC** [comment]
Thank you for providing this!

**Comment by ZheC** [comment]
Hi Yuliang, I actually mean the kitti flow 2015 training set prediction result of your method, sorry for my confusion. I was not able to run your code properly due to a different cudnn and cuda version. It will be appreciated if you can provide the prediction result on the 200 training images! Thank you!

**Comment by Yuliang-Zou** [comment]
You should be able to download them: [KITTI2012 train](https://drive.google.com/file/d/1UFFGs5TaK9JEch1uR8Ry1hKuaox4Nkb8/view?usp=sharing), [KITTI2015 train](https://drive.google.com/file/d/1L2UfrYjqj7GR8gpZ63FAHgx6JVPi-wQe/view?usp=sharing).

I save them into `.flo` format, you should be able to read them using [this function](https://github.com/vt-vl-lab/DF-Net/blob/master/core/flowlib.py#L83).

**Comment by ZheC** [comment]
Thank you for providing these files! However, I was not able to read it properly using the function. An error occurs here(https://github.com/vt-vl-lab/DF-Net/blob/master/core/flowlib.py#L96), the 'magic' number I got from your file is 52812.535, but it is expected to be 202021.25. Could you kindly help check if the flow files can be read properly on your computer? Thanks!
