### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by sakshigoyalsakshi** [vt-vl-lab/DF-Net#8]
I have installed all the configurations as specified on the page i.e.Python 3.6, TensorFlow 1.2.0, g++ 4.9, CUDA 8.0, In Ubuntu using anaconda virtual environment. But I am running into a compilation error:

backward_warp_op.cu.cc:5:54: fatal error: tensorflow/core/framework/register_types.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/visinf/home/sgoyal/Desktop/DF-Net-master/core/UnFlow/src/e2eflow/ops.py", line 53, in <module>
    op_lib = tf.load_op_library(lib_path)
  File "/visinf/home/sgoyal/anaconda3/envs/sak/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: ./backward_warp_op.so: cannot open shared object file: No such file or directory

Can you please help me out with this?

 @jbhuang0604 @sanketloke @Yuliang-Zou @LemonATsu @gaochen315

**Comment by Yuliang-Zou** [comment]
Not quite sure. Did you install the GPU version of TensorFlow?

**Comment by sakshigoyalsakshi** [comment]
Yes, I was using the GPU version. 
The problem was with the CUDA path, it was missing in the bashrc script, so the system was using CUDA-9.0 instead of 8.0

**Comment by zhangconghhh** [comment]
I meet the same problem now. How did you solve the problem?

**Comment by ReekiLee** [comment]
@zhangconghhh 
Same with me. Have you solved it?
